# GitHub Actions config
name: "Feishu Pages"
description: "Generate Feishu Wiki into a Markdown for work with Static Page Generators."
branding:
  icon: "book"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
