name: fetch blog from feishu
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Every 3 days at 00:00
    - cron: "0 0 */3 * *"
permissions:
  contents: write
jobs:
  export:
    name: get feishu pages
    runs-on: ubuntu-latest
    environment: myblog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          branch: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # or pnpm / yarn

      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install

      - name: build feishu doc
        run: npm run build # or pnpm install / yarn install / bun install

      - name: Exporting
        env:
          FEISHU_APP_ID: ${{ vars.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: "${{ vars.FEISHU_SPACE_ID}}"
          OUTPUT_DIR: ../blog
          DOC_DIR_NAME: docs
        run: npm run export

      - uses: EndBug/add-and-commit@v9
        with:
          message: commit by robot
          committer_name: GitHub Actions
          committer_email: whyzi@qq.com
          add: blog
